"""Add models

Revision ID: 11376037c14f
Revises: ce2be5bfc3e2
Create Date: 2023-04-03 02:15:16.935926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11376037c14f'
down_revision = 'ce2be5bfc3e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
