"""Add models

Revision ID: 53931311d76f
Revises: 6bc4ef717ea2
Create Date: 2023-04-03 02:19:22.182986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53931311d76f'
down_revision = '6bc4ef717ea2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
