"""Add models

Revision ID: 6bc4ef717ea2
Revises: 11376037c14f
Create Date: 2023-04-03 02:16:47.558399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc4ef717ea2'
down_revision = '11376037c14f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
